spring:
  datasource:
    url: jdbc:h2:file:~/theater
    driverClassName: org.h2.Driver
    username: sa
    password: password
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings.trace: false
#      settings.web-allow-others: false

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true
